In [1]:
import sys
sys.path.append('F:\Cambridge\Project\MHMC-for-VAE\change_of_variable')
sys.path.append('F:\Cambridge\Project\MHMC-for-VAE\hmc_pytorch')
from change_of_variable_pytorch import * 
from hmc_base_pytorch import *
from hmc_unconstrained_pytorch import *
import numpy as np
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.distributions.multivariate_normal import MultivariateNormal
from torch.distributions.normal import Normal
import matplotlib.pyplot as plt

import torch.utils.data
from torch import optim
from torchvision import datasets, transforms
from torchvision.utils import save_image
import time
import torchvision




In [41]:
def multivariate_normal_diagonal_logpdf(mean, cov_diag, x):
    n = x.shape[0] # number of samples
    k = x.shape[1] # dimension
    t1 = -0.5*(x - mean)*(1/cov_diag)*(x-mean)
    print(t1.shape)
    t1 = torch.sum(t1, dim=1)
    print(t1.shape)
    t21 = torch.ones(n)*0.5*k*torch.log(torch.tensor([2*math.pi])) 
    print(t21)
    t22 = 0.5*torch.sum(torch.log(cov_diag),dim=1)
    print(t22)
    t2 = t21 + t22
    return t1 - t2

In [42]:
mean = torch.tensor([[-0.5,0.,0.],[0.,0.,0.]])
cov_diag = torch.tensor([[1.,0.5,1.],[1.,1.,1.]])
x = torch.tensor([[0.,0.,0.],[0.,0.,0.]])

In [43]:
multivariate_normal_diagonal_logpdf(mean, cov_diag, x)

torch.Size([2, 3])
torch.Size([2])
tensor([ 2.7568,  2.7568])
tensor([-0.3466,  0.0000])


tensor([-2.5352, -2.7568])

In [34]:
mean = torch.tensor([[-0.5,0.,0.]])
cov = torch.eye(3)
cov = torch.tensor([[1.,0.,0.],[0.,0.5,0.],[0.,0.,1.]])
x = torch.tensor([[0.,0.,0.]])
m = MultivariateNormal(mean, cov)
m.requires_grad=True
m.log_prob(x)

tensor([-2.5352])

In [70]:
m = torch.tensor([[0.,0.],[0.,0.],[0.,0.]], requires_grad=True)
cov = torch.tensor([[1.,1.],[1.,1.],[1.,1.]], requires_grad=True)
x =  torch.tensor([[0.,1.],[1.,1.],[0.,0.]], requires_grad=True)
#loss = torch.mean(multivariate_normal_diagonal_logpdf(m, cov, x))
loss = torch.mean(log_prior(x))
loss.backward()
x.grad

tensor([[ 0.0000, -0.3333],
        [-0.3333, -0.3333],
        [ 0.0000,  0.0000]])